/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as TecnologiasRouteImport } from './routes/tecnologias'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as IndicadoresRouteImport } from './routes/indicadores'
import { Route as ImagensRouteImport } from './routes/imagens'
import { Route as AtividadesRouteImport } from './routes/atividades'
import { Route as IndexRouteImport } from './routes/index'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnologiasRoute = TecnologiasRouteImport.update({
  id: '/tecnologias',
  path: '/tecnologias',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresRoute = IndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagensRoute = ImagensRouteImport.update({
  id: '/imagens',
  path: '/imagens',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesRoute = AtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/imagens': typeof ImagensRoute
  '/indicadores': typeof IndicadoresRoute
  '/projetos': typeof ProjetosRoute
  '/tecnologias': typeof TecnologiasRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/imagens': typeof ImagensRoute
  '/indicadores': typeof IndicadoresRoute
  '/projetos': typeof ProjetosRoute
  '/tecnologias': typeof TecnologiasRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/imagens': typeof ImagensRoute
  '/indicadores': typeof IndicadoresRoute
  '/projetos': typeof ProjetosRoute
  '/tecnologias': typeof TecnologiasRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atividades'
    | '/imagens'
    | '/indicadores'
    | '/projetos'
    | '/tecnologias'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atividades'
    | '/imagens'
    | '/indicadores'
    | '/projetos'
    | '/tecnologias'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/atividades'
    | '/imagens'
    | '/indicadores'
    | '/projetos'
    | '/tecnologias'
    | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtividadesRoute: typeof AtividadesRoute
  ImagensRoute: typeof ImagensRoute
  IndicadoresRoute: typeof IndicadoresRoute
  ProjetosRoute: typeof ProjetosRoute
  TecnologiasRoute: typeof TecnologiasRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnologias': {
      id: '/tecnologias'
      path: '/tecnologias'
      fullPath: '/tecnologias'
      preLoaderRoute: typeof TecnologiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores': {
      id: '/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof IndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imagens': {
      id: '/imagens'
      path: '/imagens'
      fullPath: '/imagens'
      preLoaderRoute: typeof ImagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades': {
      id: '/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AtividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtividadesRoute: AtividadesRoute,
  ImagensRoute: ImagensRoute,
  IndicadoresRoute: IndicadoresRoute,
  ProjetosRoute: ProjetosRoute,
  TecnologiasRoute: TecnologiasRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
